# curl -i
#-H "Accept: application/json"
#-H "Content-Type:application/json"
#-X POST --data
#  '{"username": "johnny", "password": "password"}' "https://localhost:8080/.../request"
POST http://localhost:5500/transfer
Accept: application/json
Content-Type: application/json

{
  "amount": {
    "currency": "rur",
    "value": 10000000
  },
  "cardFromNumber": "5555555555555555",
  "cardToNumber": "2222222222222222",
  "cardFromValidTill": "11/21",
  "cardFromCVV": "123"
}

